# Generated by Django 3.0.5 on 2020-05-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='hms.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
