# Generated by Django 3.0.5 on 2020-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
